general {
    lock_cmd = pidof hyprlock || /run/current-system/sw/bin/hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 601
    on-timeout = /run/current-system/sw/bin/hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume = /run/current-system/sw/bin/hyprctl dispatch 'hl.dsp.dpms("on")'
}
