wallpaper {
    monitor =
    path = /home/vlad/documents/SYNC/wallpapers
    fit_mode = fill
    timeout = 86400
}

wallpaper {
    monitor = DP-1
    path = /home/vlad/documents/SYNC/wallpapers/tiled
    fit_mode = tile
    timeout = 86400
}
