"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
	# Hopping
	{ on = "e", run = "arrow prev", desc = "Previous file" },
	{ on = "n", run = "arrow next", desc = "Next file" },

	# Navigation
	{ on = "m", run = "leave", desc = "Back to the parent directory" },
	{ on = "i", run = "enter", desc = "Enter the child directory" },

	{ on = "M", run = "back",    desc = "Back to previous directory" },
	{ on = "I", run = "forward", desc = "Forward to next directory" },

	# Seeking
	{ on = "E", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "N", run = "seek 5",  desc = "Seek down 5 units in the preview" },
]

[tasks]
prepend_keymap = [
	{ on = "e", run = "arrow prev", desc = "Previous task" },
	{ on = "n", run = "arrow next", desc = "Next task" },
]

[spot]
prepend_keymap = [
	{ on = "m", run = "swipe prev", desc = "Swipe to previous file" },
	{ on = "n", run = "arrow next", desc = "Next line" },
	{ on = "e", run = "arrow prev", desc = "Previous line" },
	{ on = "i", run = "swipe next", desc = "Swipe to next file" },
]

[pick]
prepend_keymap = [
	{ on = "e", run = "arrow prev", desc = "Previous option" },
	{ on = "n", run = "arrow next", desc = "Next option" },
]

[confirm]
prepend_keymap = [
	{ on = "e", run = "arrow prev", desc = "Previous line" },
	{ on = "n", run = "arrow next", desc = "Next line" },
]

[help]
prepend_keymap = [
	{ on = "e", run = "arrow prev", desc = "Previous line" },
	{ on = "n", run = "arrow next", desc = "Next line" },

]

